server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092
    consumer:
      bootstrap-servers: localhost:29092, localhost:39092
      group-id: myGroup
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/wikimedia
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
